/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CubeJS.Gateway.Client.Client.OpenAPIDateConverter;

namespace CubeJS.Gateway.Client.Model
{
    /// <summary>
    /// V1LoadRequestQueryFilterLogicalAnd
    /// </summary>
    [DataContract(Name = "V1LoadRequestQueryFilterLogicalAnd")]
    public partial class V1LoadRequestQueryFilterLogicalAnd : IEquatable<V1LoadRequestQueryFilterLogicalAnd>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1LoadRequestQueryFilterLogicalAnd" /> class.
        /// </summary>
        /// <param name="and">and.</param>
        public V1LoadRequestQueryFilterLogicalAnd(List<Object> and = default(List<Object>))
        {
            this.And = and;
        }

        /// <summary>
        /// Gets or Sets And
        /// </summary>
        [DataMember(Name = "and", EmitDefaultValue = false)]
        public List<Object> And { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1LoadRequestQueryFilterLogicalAnd {\n");
            sb.Append("  And: ").Append(And).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as V1LoadRequestQueryFilterLogicalAnd);
        }

        /// <summary>
        /// Returns true if V1LoadRequestQueryFilterLogicalAnd instances are equal
        /// </summary>
        /// <param name="input">Instance of V1LoadRequestQueryFilterLogicalAnd to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1LoadRequestQueryFilterLogicalAnd input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.And == input.And ||
                    this.And != null &&
                    input.And != null &&
                    this.And.SequenceEqual(input.And)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.And != null)
                {
                    hashCode = (hashCode * 59) + this.And.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
