/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CubeJS.Gateway.Client.Client.OpenAPIDateConverter;

namespace CubeJS.Gateway.Client.Model
{
    /// <summary>
    /// V1LoadRequestQueryFilterLogicalOr
    /// </summary>
    [DataContract(Name = "V1LoadRequestQueryFilterLogicalOr")]
    public partial class V1LoadRequestQueryFilterLogicalOr : IEquatable<V1LoadRequestQueryFilterLogicalOr>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1LoadRequestQueryFilterLogicalOr" /> class.
        /// </summary>
        /// <param name="or">or.</param>
        public V1LoadRequestQueryFilterLogicalOr(List<Object> or = default(List<Object>))
        {
            this.Or = or;
        }

        /// <summary>
        /// Gets or Sets Or
        /// </summary>
        [DataMember(Name = "or", EmitDefaultValue = false)]
        public List<Object> Or { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1LoadRequestQueryFilterLogicalOr {\n");
            sb.Append("  Or: ").Append(Or).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as V1LoadRequestQueryFilterLogicalOr);
        }

        /// <summary>
        /// Returns true if V1LoadRequestQueryFilterLogicalOr instances are equal
        /// </summary>
        /// <param name="input">Instance of V1LoadRequestQueryFilterLogicalOr to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1LoadRequestQueryFilterLogicalOr input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Or == input.Or ||
                    this.Or != null &&
                    input.Or != null &&
                    this.Or.SequenceEqual(input.Or)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Or != null)
                {
                    hashCode = (hashCode * 59) + this.Or.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
