/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CubeJS.Gateway.Client.Client.OpenAPIDateConverter;

namespace CubeJS.Gateway.Client.Model
{
    /// <summary>
    /// V1MetaResponse
    /// </summary>
    [DataContract(Name = "V1MetaResponse")]
    public partial class V1MetaResponse : IEquatable<V1MetaResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1MetaResponse" /> class.
        /// </summary>
        /// <param name="cubes">cubes.</param>
        public V1MetaResponse(List<V1CubeMeta> cubes = default(List<V1CubeMeta>))
        {
            this.Cubes = cubes;
        }

        /// <summary>
        /// Gets or Sets Cubes
        /// </summary>
        [DataMember(Name = "cubes", EmitDefaultValue = false)]
        public List<V1CubeMeta> Cubes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1MetaResponse {\n");
            sb.Append("  Cubes: ").Append(Cubes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as V1MetaResponse);
        }

        /// <summary>
        /// Returns true if V1MetaResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of V1MetaResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1MetaResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cubes == input.Cubes ||
                    this.Cubes != null &&
                    input.Cubes != null &&
                    this.Cubes.SequenceEqual(input.Cubes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cubes != null)
                {
                    hashCode = (hashCode * 59) + this.Cubes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
