/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1CubeMetaSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CubeMetaSegmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CubeMetaSegment
        //private V1CubeMetaSegment instance;

        public V1CubeMetaSegmentTests()
        {
            // TODO uncomment below to create an instance of V1CubeMetaSegment
            //instance = new V1CubeMetaSegment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CubeMetaSegment
        /// </summary>
        [Fact]
        public void V1CubeMetaSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CubeMetaSegment
            //Assert.IsType<V1CubeMetaSegment>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'ShortTitle'
        /// </summary>
        [Fact]
        public void ShortTitleTest()
        {
            // TODO unit test for the property 'ShortTitle'
        }

    }

}
