/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1CubeMetaDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CubeMetaDimensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CubeMetaDimension
        //private V1CubeMetaDimension instance;

        public V1CubeMetaDimensionTests()
        {
            // TODO uncomment below to create an instance of V1CubeMetaDimension
            //instance = new V1CubeMetaDimension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CubeMetaDimension
        /// </summary>
        [Fact]
        public void V1CubeMetaDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CubeMetaDimension
            //Assert.IsType<V1CubeMetaDimension>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
