/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1CubeMetaMeasure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CubeMetaMeasureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CubeMetaMeasure
        //private V1CubeMetaMeasure instance;

        public V1CubeMetaMeasureTests()
        {
            // TODO uncomment below to create an instance of V1CubeMetaMeasure
            //instance = new V1CubeMetaMeasure();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CubeMetaMeasure
        /// </summary>
        [Fact]
        public void V1CubeMetaMeasureInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CubeMetaMeasure
            //Assert.IsType<V1CubeMetaMeasure>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AggType'
        /// </summary>
        [Fact]
        public void AggTypeTest()
        {
            // TODO unit test for the property 'AggType'
        }

    }

}
