/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadRequest
        //private V1LoadRequest instance;

        public V1LoadRequestTests()
        {
            // TODO uncomment below to create an instance of V1LoadRequest
            //instance = new V1LoadRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadRequest
        /// </summary>
        [Fact]
        public void V1LoadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadRequest
            //Assert.IsType<V1LoadRequest>(instance);
        }


        /// <summary>
        /// Test the property 'QueryType'
        /// </summary>
        [Fact]
        public void QueryTypeTest()
        {
            // TODO unit test for the property 'QueryType'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

    }

}
