/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadResponse
        //private V1LoadResponse instance;

        public V1LoadResponseTests()
        {
            // TODO uncomment below to create an instance of V1LoadResponse
            //instance = new V1LoadResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadResponse
        /// </summary>
        [Fact]
        public void V1LoadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadResponse
            //Assert.IsType<V1LoadResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PivotQuery'
        /// </summary>
        [Fact]
        public void PivotQueryTest()
        {
            // TODO unit test for the property 'PivotQuery'
        }
        /// <summary>
        /// Test the property 'SlowQuery'
        /// </summary>
        [Fact]
        public void SlowQueryTest()
        {
            // TODO unit test for the property 'SlowQuery'
        }
        /// <summary>
        /// Test the property 'QueryType'
        /// </summary>
        [Fact]
        public void QueryTypeTest()
        {
            // TODO unit test for the property 'QueryType'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
