/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadResult
        //private V1LoadResult instance;

        public V1LoadResultTests()
        {
            // TODO uncomment below to create an instance of V1LoadResult
            //instance = new V1LoadResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadResult
        /// </summary>
        [Fact]
        public void V1LoadResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadResult
            //Assert.IsType<V1LoadResult>(instance);
        }


        /// <summary>
        /// Test the property 'DataSource'
        /// </summary>
        [Fact]
        public void DataSourceTest()
        {
            // TODO unit test for the property 'DataSource'
        }
        /// <summary>
        /// Test the property 'Annotation'
        /// </summary>
        [Fact]
        public void AnnotationTest()
        {
            // TODO unit test for the property 'Annotation'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'RefreshKeyValues'
        /// </summary>
        [Fact]
        public void RefreshKeyValuesTest()
        {
            // TODO unit test for the property 'RefreshKeyValues'
        }

    }

}
