/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadResultAnnotation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadResultAnnotationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadResultAnnotation
        //private V1LoadResultAnnotation instance;

        public V1LoadResultAnnotationTests()
        {
            // TODO uncomment below to create an instance of V1LoadResultAnnotation
            //instance = new V1LoadResultAnnotation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadResultAnnotation
        /// </summary>
        [Fact]
        public void V1LoadResultAnnotationInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadResultAnnotation
            //Assert.IsType<V1LoadResultAnnotation>(instance);
        }


        /// <summary>
        /// Test the property 'Measures'
        /// </summary>
        [Fact]
        public void MeasuresTest()
        {
            // TODO unit test for the property 'Measures'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
        /// <summary>
        /// Test the property 'TimeDimensions'
        /// </summary>
        [Fact]
        public void TimeDimensionsTest()
        {
            // TODO unit test for the property 'TimeDimensions'
        }

    }

}
