/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadRequestQueryTimeDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadRequestQueryTimeDimensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadRequestQueryTimeDimension
        //private V1LoadRequestQueryTimeDimension instance;

        public V1LoadRequestQueryTimeDimensionTests()
        {
            // TODO uncomment below to create an instance of V1LoadRequestQueryTimeDimension
            //instance = new V1LoadRequestQueryTimeDimension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadRequestQueryTimeDimension
        /// </summary>
        [Fact]
        public void V1LoadRequestQueryTimeDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadRequestQueryTimeDimension
            //Assert.IsType<V1LoadRequestQueryTimeDimension>(instance);
        }


        /// <summary>
        /// Test the property 'Dimension'
        /// </summary>
        [Fact]
        public void DimensionTest()
        {
            // TODO unit test for the property 'Dimension'
        }
        /// <summary>
        /// Test the property 'Granularity'
        /// </summary>
        [Fact]
        public void GranularityTest()
        {
            // TODO unit test for the property 'Granularity'
        }
        /// <summary>
        /// Test the property 'DateRange'
        /// </summary>
        [Fact]
        public void DateRangeTest()
        {
            // TODO unit test for the property 'DateRange'
        }

    }

}
