/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadRequestQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadRequestQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadRequestQuery
        //private V1LoadRequestQuery instance;

        public V1LoadRequestQueryTests()
        {
            // TODO uncomment below to create an instance of V1LoadRequestQuery
            //instance = new V1LoadRequestQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadRequestQuery
        /// </summary>
        [Fact]
        public void V1LoadRequestQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadRequestQuery
            //Assert.IsType<V1LoadRequestQuery>(instance);
        }


        /// <summary>
        /// Test the property 'Measures'
        /// </summary>
        [Fact]
        public void MeasuresTest()
        {
            // TODO unit test for the property 'Measures'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Fact]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
        /// <summary>
        /// Test the property 'TimeDimensions'
        /// </summary>
        [Fact]
        public void TimeDimensionsTest()
        {
            // TODO unit test for the property 'TimeDimensions'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

    }

}
