/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CubeJS.Gateway.Client.Model;
using CubeJS.Gateway.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CubeJS.Gateway.Client.Test.Model
{
    /// <summary>
    ///  Class for testing V1LoadRequestQueryFilterBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LoadRequestQueryFilterBaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LoadRequestQueryFilterBase
        //private V1LoadRequestQueryFilterBase instance;

        public V1LoadRequestQueryFilterBaseTests()
        {
            // TODO uncomment below to create an instance of V1LoadRequestQueryFilterBase
            //instance = new V1LoadRequestQueryFilterBase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LoadRequestQueryFilterBase
        /// </summary>
        [Fact]
        public void V1LoadRequestQueryFilterBaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1LoadRequestQueryFilterBase
            //Assert.IsType<V1LoadRequestQueryFilterBase>(instance);
        }


        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Fact]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
