/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using CubeJS.Gateway.Client.Client;
using CubeJS.Gateway.Client.Model;

namespace CubeJS.Gateway.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Load data via Cube JSON Query
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>V1LoadResponse</returns>
        V1LoadResponse LoadV1(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0);

        /// <summary>
        /// Load data via Cube JSON Query
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of V1LoadResponse</returns>
        ApiResponse<V1LoadResponse> LoadV1WithHttpInfo(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0);
        /// <summary>
        /// Load Metadata
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>V1MetaResponse</returns>
        V1MetaResponse MetaV1(int operationIndex = 0);

        /// <summary>
        /// Load Metadata
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of V1MetaResponse</returns>
        ApiResponse<V1MetaResponse> MetaV1WithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Load data via Cube JSON Query
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1LoadResponse</returns>
        System.Threading.Tasks.Task<V1LoadResponse> LoadV1Async(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Load data via Cube JSON Query
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1LoadResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1LoadResponse>> LoadV1WithHttpInfoAsync(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Load Metadata
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1MetaResponse</returns>
        System.Threading.Tasks.Task<V1MetaResponse> MetaV1Async(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Load Metadata
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1MetaResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1MetaResponse>> MetaV1WithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private CubeJS.Gateway.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = CubeJS.Gateway.Client.Client.Configuration.MergeConfigurations(
                CubeJS.Gateway.Client.Client.GlobalConfiguration.Instance,
                new CubeJS.Gateway.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new CubeJS.Gateway.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CubeJS.Gateway.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = CubeJS.Gateway.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(CubeJS.Gateway.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CubeJS.Gateway.Client.Client.Configuration.MergeConfigurations(
                CubeJS.Gateway.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new CubeJS.Gateway.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new CubeJS.Gateway.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = CubeJS.Gateway.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DefaultApi(CubeJS.Gateway.Client.Client.ISynchronousClient client, CubeJS.Gateway.Client.Client.IAsynchronousClient asyncClient, CubeJS.Gateway.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CubeJS.Gateway.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CubeJS.Gateway.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CubeJS.Gateway.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CubeJS.Gateway.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CubeJS.Gateway.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Load data via Cube JSON Query 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>V1LoadResponse</returns>
        public V1LoadResponse LoadV1(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0)
        {
            CubeJS.Gateway.Client.Client.ApiResponse<V1LoadResponse> localVarResponse = LoadV1WithHttpInfo(v1LoadRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Load data via Cube JSON Query 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of V1LoadResponse</returns>
        public CubeJS.Gateway.Client.Client.ApiResponse<V1LoadResponse> LoadV1WithHttpInfo(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0)
        {
            CubeJS.Gateway.Client.Client.RequestOptions localVarRequestOptions = new CubeJS.Gateway.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = v1LoadRequest;

            localVarRequestOptions.Operation = "DefaultApi.LoadV1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<V1LoadResponse>("/v1/load", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("LoadV1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Load data via Cube JSON Query 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1LoadResponse</returns>
        public async System.Threading.Tasks.Task<V1LoadResponse> LoadV1Async(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CubeJS.Gateway.Client.Client.ApiResponse<V1LoadResponse> localVarResponse = await LoadV1WithHttpInfoAsync(v1LoadRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Load data via Cube JSON Query 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1LoadRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1LoadResponse)</returns>
        public async System.Threading.Tasks.Task<CubeJS.Gateway.Client.Client.ApiResponse<V1LoadResponse>> LoadV1WithHttpInfoAsync(V1LoadRequest? v1LoadRequest = default(V1LoadRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            CubeJS.Gateway.Client.Client.RequestOptions localVarRequestOptions = new CubeJS.Gateway.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = v1LoadRequest;

            localVarRequestOptions.Operation = "DefaultApi.LoadV1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<V1LoadResponse>("/v1/load", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("LoadV1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Load Metadata 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>V1MetaResponse</returns>
        public V1MetaResponse MetaV1(int operationIndex = 0)
        {
            CubeJS.Gateway.Client.Client.ApiResponse<V1MetaResponse> localVarResponse = MetaV1WithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Load Metadata 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of V1MetaResponse</returns>
        public CubeJS.Gateway.Client.Client.ApiResponse<V1MetaResponse> MetaV1WithHttpInfo(int operationIndex = 0)
        {
            CubeJS.Gateway.Client.Client.RequestOptions localVarRequestOptions = new CubeJS.Gateway.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "DefaultApi.MetaV1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<V1MetaResponse>("/v1/meta", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MetaV1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Load Metadata 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1MetaResponse</returns>
        public async System.Threading.Tasks.Task<V1MetaResponse> MetaV1Async(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            CubeJS.Gateway.Client.Client.ApiResponse<V1MetaResponse> localVarResponse = await MetaV1WithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Load Metadata 
        /// </summary>
        /// <exception cref="CubeJS.Gateway.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1MetaResponse)</returns>
        public async System.Threading.Tasks.Task<CubeJS.Gateway.Client.Client.ApiResponse<V1MetaResponse>> MetaV1WithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            CubeJS.Gateway.Client.Client.RequestOptions localVarRequestOptions = new CubeJS.Gateway.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = CubeJS.Gateway.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "DefaultApi.MetaV1";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<V1MetaResponse>("/v1/meta", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MetaV1", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
