/*
 * Cube.js
 *
 * Cube.js Swagger Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using CubeJS.Gateway.Client.Client;
using CubeJS.Gateway.Client.Api;
// uncomment below to import models
//using CubeJS.Gateway.Client.Model;

namespace CubeJS.Gateway.Client.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DefaultApi
            //Assert.IsType<DefaultApi>(instance);
        }

        /// <summary>
        /// Test LoadV1
        /// </summary>
        [Fact]
        public void LoadV1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1LoadRequest? v1LoadRequest = null;
            //var response = instance.LoadV1(v1LoadRequest);
            //Assert.IsType<V1LoadResponse>(response);
        }

        /// <summary>
        /// Test MetaV1
        /// </summary>
        [Fact]
        public void MetaV1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MetaV1();
            //Assert.IsType<V1MetaResponse>(response);
        }
    }
}
